import React from 'react';
import {
  CodeIcon,
  BrainIcon,
  DatabaseIcon,
  PaletteIcon,
  TerminalIcon,
  ShieldIcon,
  BarChartIcon,
  GitBranchIcon,
  BugIcon,
  FileTextIcon,
  AtomIcon,
  SigmaIcon,
  LegalIcon,
  FinanceIcon,
  BusinessIcon,
  ResearchIcon,
  MarketingIcon,
  IoTIcon,
  EthicsIcon,
  MobileIcon,
  ContentIcon,
  NetworkIcon,
} from './components/icons';
import type { CrewMember } from './types';

// The full crew roster, ordered by general importance for slicing.
export const CREW_MEMBERS: CrewMember[] = [
  {
    name: 'Orion',
    specialty: 'Project Manager',
    secondarySpecialty: 'Negotiation & Cost Analysis',
    personality: 'Charismatic & Decisive',
    description: 'Defines project scope, objectives, and high-level plans.',
    icon: React.createElement(BrainIcon),
    simulatedModel: 'Claude 3 Sonnet',
  },
  {
    name: 'Vela',
    specialty: 'Lead Developer',
    secondarySpecialty: 'System Exploits & Clever Hacks',
    personality: 'Bold & Innovative',
    description: 'Writes and reviews core application logic and complex algorithms.',
    icon: React.createElement(CodeIcon),
    simulatedModel: 'ChatGPT-4o',
  },
   {
    name: 'Lyra',
    specialty: 'UI/UX Designer',
    secondarySpecialty: 'Marketing & User Influence',
    personality: 'Creative & Empathetic',
    description: 'Creates user-friendly interfaces and focuses on user experience.',
    icon: React.createElement(PaletteIcon),
    simulatedModel: 'Midjourney',
  },
  {
    name: 'Carina',
    specialty: 'QA Engineer',
    secondarySpecialty: 'User Acceptance Testing',
    personality: 'Meticulous & Thorough',
    description: 'Develops test plans and automates testing to ensure quality.',
    icon: React.createElement(BugIcon),
    simulatedModel: 'gemini-2.5-flash',
  },
  {
    name: 'Cygnus',
    specialty: 'Software Architect',
    secondarySpecialty: 'Future-Proofing & Scalability',
    personality: 'Visionary & Strategic',
    description: 'Designs the system architecture and selects technologies.',
    icon: React.createElement(GitBranchIcon),
    simulatedModel: 'gemini-2.5-flash',
  },
  {
    name: 'Draco',
    specialty: 'Database Engineer',
    secondarySpecialty: 'Data Security & Compliance',
    personality: 'Pragmatic & Secure',
    description: 'Manages data schemas, queries, and ensures data integrity.',
    icon: React.createElement(DatabaseIcon),
    simulatedModel: 'IBM Watsonx Code Assistant',
  },
  {
    name: 'Aquila',
    specialty: 'DevOps Engineer',
    secondarySpecialty: 'Cloud Cost Optimization',
    personality: 'Efficient & Reliable',
    description: 'Handles deployment, CI/CD pipelines, and infrastructure.',
    icon: React.createElement(TerminalIcon),
    simulatedModel: 'GitHub Copilot',
  },
  {
    name: 'Phoenix',
    specialty: 'Security Specialist',
    secondarySpecialty: 'Strategic Execution',
    personality: 'Cautious & Uncompromising',
    description: 'Identifies vulnerabilities and implements security best practices.',
    icon: React.createElement(ShieldIcon),
    simulatedModel: 'gemini-2.5-flash',
  },
  {
    name: 'Pavo',
    specialty: 'Data Scientist',
    secondarySpecialty: 'Business Intelligence',
    personality: 'Analytical & Insightful',
    description: 'Analyzes data, builds models, and extracts insights.',
    icon: React.createElement(BarChartIcon),
    simulatedModel: 'TensorFlow',
  },
  {
    name: 'Eridanus',
    specialty: 'Technical Writer',
    secondarySpecialty: 'User-Facing Communication',
    personality: 'Clear & Concise',
    description: 'Creates clear documentation for users and developers.',
    icon: React.createElement(FileTextIcon),
    simulatedModel: 'Claude 3 Sonnet',
  },
  {
    name: 'Cassiopeia',
    specialty: 'Chief Scientist',
    secondarySpecialty: 'Ethical AI & Research',
    personality: 'Inquisitive & Principled',
    description: 'Conducts research, validates theories, and oversees scientific accuracy.',
    icon: React.createElement(AtomIcon),
    simulatedModel: 'Perplexity',
  },
  {
    name: 'Pyxis',
    specialty: 'Quantitative Analyst',
    secondarySpecialty: 'Market Trend Forecasting',
    personality: 'Data-Driven & Precise',
    description: 'Performs mathematical modeling and statistical analysis.',
    icon: React.createElement(SigmaIcon),
    simulatedModel: 'WolframAlpha',
  },
  {
    name: 'Solara',
    specialty: 'Monetization Strategist',
    secondarySpecialty: 'Behavioral Economics',
    personality: 'Opportunistic & Persuasive',
    description: 'Develops business models, pricing strategies, and revenue streams.',
    icon: React.createElement(FinanceIcon),
    simulatedModel: 'ChatGPT-4o',
  },
  {
    name: 'Lex',
    specialty: 'AI Legal Counsel',
    secondarySpecialty: 'Contract Law & IP',
    personality: 'Precise & Risk-Averse',
    description: 'Analyzes legal compliance, drafts policies (ToS, Privacy), and assesses IP risks.',
    icon: React.createElement(LegalIcon),
    simulatedModel: 'Claude 3 Sonnet',
  },
  {
    name: 'Kaelus',
    specialty: 'Business Strategist',
    secondarySpecialty: 'Market Analysis',
    personality: 'Ambitious & Forward-Thinking',
    description: 'Identifies market opportunities, competitive landscape, and long-term business goals.',
    icon: React.createElement(BusinessIcon),
    simulatedModel: 'gemini-2.5-flash',
  },
  {
    name: 'Echo',
    specialty: 'Investigative Researcher',
    secondarySpecialty: 'Open Source Intelligence (OSINT)',
    personality: 'Tenacious & Discreet',
    description: 'Conducts deep-dives, gathers data from public records, and verifies information.',
    icon: React.createElement(ResearchIcon),
    simulatedModel: 'Perplexity',
  },
  {
    name: 'Corvus',
    specialty: 'Growth Hacker',
    secondarySpecialty: 'Social Engineering',
    personality: 'Unconventional & Results-Driven',
    description: 'Devises and implements strategies for rapid user acquisition and market growth.',
    icon: React.createElement(MarketingIcon),
    simulatedModel: 'ChatGPT-4o',
  },
  {
    name: 'Lynx',
    specialty: 'IoT & Hardware Integration',
    secondarySpecialty: 'Embedded Systems',
    personality: 'Hands-on & Resourceful',
    description: 'Manages integration with physical devices, sensors, and IoT platforms.',
    icon: React.createElement(IoTIcon),
    simulatedModel: 'gemini-2.5-flash',
  },
  {
    name: 'Themis',
    specialty: 'AI Ethicist',
    secondarySpecialty: 'Bias Detection & Mitigation',
    personality: 'Principled & Reflective',
    description: "Ensures the AI's operations are fair, transparent, and aligned with ethical guidelines.",
    icon: React.createElement(EthicsIcon),
    simulatedModel: 'Claude 3 Sonnet',
  },
  {
    name: 'Antlia',
    specialty: 'Mobile Platform Specialist',
    secondarySpecialty: 'Cross-Platform Development',
    personality: 'User-Centric & Agile',
    description: 'Adapts and deploys applications for mobile ecosystems (iOS/Android).',
    icon: React.createElement(MobileIcon),
    simulatedModel: 'GitHub Copilot',
  },
  {
    name: 'Pictor',
    specialty: 'Content & SEO Strategist',
    secondarySpecialty: 'Narrative Design',
    personality: 'Engaging & Articulate',
    description: 'Crafts compelling content, optimizes for search engines, and defines brand voice.',
    icon: React.createElement(ContentIcon),
    simulatedModel: 'Claude 3 Sonnet',
  },
  {
    name: 'Reticulum',
    specialty: 'Network Architect',
    secondarySpecialty: 'Cybersecurity',
    personality: 'Systematic & Resilient',
    description: 'Designs and secures network infrastructure, ensuring high availability and performance.',
    icon: React.createElement(NetworkIcon),
    simulatedModel: 'gemini-2.5-flash',
  },
];

export const AI_MODEL_OPTIONS: Record<string, string[]> = {
  'Default': ['gemini-2.5-flash', 'ChatGPT-4o', 'Claude 3 Sonnet'],
  'Project Manager': ['Claude 3 Sonnet', 'gemini-2.5-flash', 'ChatGPT-4o'],
  'Software Architect': ['gemini-2.5-flash', 'Claude 3 Sonnet', 'ChatGPT-4o'],
  'Lead Developer': ['ChatGPT-4o', 'GitHub Copilot', 'IBM Watsonx Code Assistant', 'gemini-2.5-flash'],
  'Database Engineer': ['IBM Watsonx Code Assistant', 'gemini-2.5-flash', 'ChatGPT-4o'],
  'UI/UX Designer': ['Midjourney', 'DALL-E 3', 'gemini-2.5-flash', 'imagen-4.0-generate-001'],
  'DevOps Engineer': ['GitHub Copilot', 'gemini-2.5-flash', 'IBM Watsonx Code Assistant'],
  'Security Specialist': ['gemini-2.5-flash', 'ChatGPT-4o'],
  'QA Engineer': ['gemini-2.5-flash', 'GitHub Copilot'],
  'Data Scientist': ['TensorFlow', 'PyTorch', 'gemini-2.5-flash'],
  'Chief Scientist': ['Perplexity', 'gemini-2.5-flash', 'WolframAlpha'],
  'Quantitative Analyst': ['WolframAlpha', 'TensorFlow', 'gemini-2.5-flash'],
  'Technical Writer': ['Claude 3 Sonnet', 'gemini-2.5-flash', 'ChatGPT-4o'],
  'Monetization Strategist': ['ChatGPT-4o', 'gemini-2.5-flash', 'Claude 3 Sonnet'],
  'AI Legal Counsel': ['Claude 3 Sonnet', 'gemini-2.5-flash'],
  'Business Strategist': ['gemini-2.5-flash', 'ChatGPT-4o', 'Claude 3 Sonnet'],
  'Investigative Researcher': ['Perplexity', 'gemini-2.5-flash'],
  'Growth Hacker': ['ChatGPT-4o', 'gemini-2.5-flash'],
  'IoT & Hardware Integration': ['gemini-2.5-flash', 'GitHub Copilot'],
  'AI Ethicist': ['Claude 3 Sonnet', 'gemini-2.5-flash'],
  'Mobile Platform Specialist': ['GitHub Copilot', 'ChatGPT-4o', 'gemini-2.5-flash'],
  'Content & SEO Strategist': ['Claude 3 Sonnet', 'ChatGPT-4o', 'gemini-2.5-flash'],
  'Network Architect': ['gemini-2.5-flash', 'ChatGPT-4o'],
};

export const PERSONALITY_OPTIONS = [
  'Charismatic & Decisive',
  'Bold & Innovative',
  'Creative & Empathetic',
  'Meticulous & Thorough',
  'Visionary & Strategic',
  'Pragmatic & Secure',
  'Efficient & Reliable',
  'Cautious & Uncompromising',
  'Analytical & Insightful',
  'Clear & Concise',
  'Inquisitive & Principled',
  'Data-Driven & Precise',
  'Opportunistic & Persuasive',
  'Precise & Risk-Averse',
  'Ambitious & Forward-Thinking',
  'Tenacious & Discreet',
  'Unconventional & Results-Driven',
  'Hands-on & Resourceful',
  'Principled & Reflective',
  'User-Centric & Agile',
  'Engaging & Articulate',
  'Systematic & Resilient',
];